Валидация пароля
antipod237/ipc_practice pull request #31
Opened 2022-05-19 19:01 UTC by AbsolutelyH

#2

2022-05-20 13:43 UTC, kzagorulko requested changes

2022-05-20 13:43 UTC, kzagorulko commented on backend/erpsystem/core/users/password_strength.py
> +        return False
Не просто так в ищьюсе было написано не изобретать велосипед 

![image](https://user-images.githubusercontent.com/31614542/169540394-9ee4b5a0-4db8-424d-b954-0f87aa8fa56b.png)

Пароли: `mtRe2 31` и `23k\n\t1KK` считаются валидными, хотя это явно не так

Лучше использовать для таких вещей библиотеки, которые под это заточены

2022-05-22 16:59 UTC, elena-mayorova commented
Функцию проверки ты создал, но ее еще нужно подрубить в ресурс приложения (в `custom_checks` методов `post` и `patch`, по аналогии с `validate_role`), чтобы она не просто висела, а использовалась

2022-05-25 11:13 UTC, kzagorulko approved these changes

2022-05-25 16:13 UTC, merged